#!/usr/bin/env bash
#----------------------------------------------------------------------------------+
# autor  : Abner Benedito
# github : ghostkill73
#
# licença: GPLv3+
#----------------------------------------------------------------------------------+
#
# CryptoKnightX é uma fork!
# Projeto originado por Jefferson Rocha:
# <https://notabug.org/slackjeff/knight>
#
#----------------------------------------------------------------------------------+
# Copyright (C) 2024-2025  Abner Benedito
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#----------------------------------------------------------------------------------+
# DESCRIÇÃO:
#
# O objetivo deste software é manter a segurança e integridade de seus arquivos.
# O CKX foi feito em sua maior parte em bash script puro, isso significa que ele
# funcionará corretamenta na maioria das distribuições Linux/BSD.
#
# Dependências fundamentais:
#	- GNU Tar 1.30+
#	- GNU Privacy Guard (gpg) 2.2.7+
#	- GNU Bash (Bourne-Again Shell) 3+
# *** o software ainda está em fase de testes, a versão das dependências
# podem não corresponder com oque está sendo exigido. ***
#
# Avisos:
#
#	* * * Os desenvolvedores deste software não se responsabilizam
#	pelo uso indevido desta ferramenta; * * *
#
#	* O CKX não segue o padrão SHELL POSIX;
#
#	* Certifique-se de não perder sua senha dos arquivos
#	criptografados, se perder já era! a chance de conseguir
#	quebrar a criptografia é mínima;
#
#	* Nenhum sistema é seguro, proteja sua integridade.
#	tenha em mente que um dia você será hackeado, procure
#	reduzir riscos. Não utilize somente o CKX para proteger
#	seus arquivos mas também proteja sua máquina como um
#	todo.
#
# Boas práticas:
#
#	* ter uma senha de usuário root forte;
#
#	* criptografar o armazenamento(HDD,SSD,...) da máquina;
#
#	* utilizar uma senha com no mínimo 8 caracteres
#	sem possuir um padrão óbvio, colocando caracteres
#	como `#$@%`;
#
#	* troca periódica das senhas;
#
#	* se possível utilize gerenciadores de senhas off-line
#	como o `keepassXC` por exemplo, donde possibilita copiar
#	e colar a sua senha;
#
#	* Fazer backups constantes e armazená-los em um local
#	seguro;
#
# Contribuindo:
#
#	* Sempre procure fazer um script puro, utilizando os recursos
#	que o BASH possue;
#
#	* Não adicione utilitários terceiros não-livres e/ou que fujam
# 	do escopo das dependências fundamentais do software;
#
#	* Certifique-se de que as modificações estão corretas, livres
#	de problemas.
#
#	Repositório: https://github.com/ghostkill73/CryptoKnightX
#
#----------------------------------------------------------------------------------+
# shellcheck disable=SC2155
# shellcheck disable=SC2164

########################################################################################
#
# DEPS
#
########################################################################################

[[ -n "$(type -P gpg)" ]] || {
	echo "$0: 'gpg' não está instalado em seu sistema."
	exit 1
}

[[ -n "$(type -P tar)" ]] || {
	echo "$0: 'tar' não está instalado em seu sistema."
	exit 1
}

########################################################################################
#
# CONFIGS
#
########################################################################################

declare SOFTWARE_NAME="CryptoKnightX"
declare SOFTWARE_VERSION="v0.0.6"

declare CKX_DEFAULT_DIR="${XDG_DATA_HOME:=${HOME:=/home/$USER}/.local/share}/ckx"
declare CKX_CONFIGS_DIR="${CKX_DEFAULT_DIR}/config"

declare -i TRUE=0
declare -i FALSE=1
declare -i ERROR=2

export GPG_TTY=$(tty)

########################################################################################
#
# CONFIG FILE
#
########################################################################################

# shellcheck disable=SC1091
source "${CKX_CONFIGS_DIR}/ckx.conf" 2>&-

: "${S2K_MODE:=3}"
: "${S2K_COUNT:=65011712}"
: "${S2K_DIGEST_ALGO:=SHA512}"
: "${S2K_CIPHER_ALGO:=TWOFISH}"

declare -ar GPG_ENC_OPTS=(
	--quiet
	--no-symkey-cache
	--compress-algo 0
	--s2k-mode "$S2K_MODE"
	--s2k-count "$S2K_COUNT"
	--s2k-digest-algo "$S2K_DIGEST_ALGO"
	--s2k-cipher-algo "$S2K_CIPHER_ALGO"
)
declare -ar GPG_DEC_OPTS=( --yes --quiet --no-symkey-cache )

########################################################################################
#
# Utils
#
########################################################################################

msg() {
	printf '%b\n' "$*" >&2
}

error() {
	msg "\e[1;31m[!] ${*}\e[m"
}

fatal() {
	msg "\e[1;41m[!!] ${*}\e[m"

	exit "$ERROR"
}

sucess() {
	msg "\e[1;32m[*] ${*}\e[m"
}

warn() {
	msg "\e[1;33m[#] ${*}\e[m"
}

########################################################################################
#
# Informações
#
########################################################################################

display_default_message() {
	msg "$SOFTWARE_NAME $SOFTWARE_VERSION"
	msg "Copyright (C) 2024-2025 Abner Benedito"
	msg "License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>"
	msg "This is free software: you are free to change and redistribute it."
	msg "There is NO WARRANTY, to the extent permitted by law."
}

display_license() {
	msg "$SOFTWARE_NAME $SOFTWARE_VERSION Copyright (C) 2024-2025 Abner Benedito"
	msg ""
	msg " This program is free software: you can redistribute it and/or modify"
	msg " it under the terms of the GNU General Public License as published by"
	msg " the Free Software Foundation, either version 3 of the License, or"
	msg " (at your option) any later version."
	msg ""
	msg " This program is distributed in the hope that it will be useful,"
	msg " but WITHOUT ANY WARRANTY; without even the implied warranty of"
	msg " MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"
	msg " GNU General Public License for more details."
	msg ""
	msg " You should have received a copy of the GNU General Public License"
	msg " along with this program.  If not, see <https://www.gnu.org/licenses/>."

	exit "$TRUE"
}

display_version() {
	msg "${SOFTWARE_NAME} ${SOFTWARE_VERSION}"

	exit "$TRUE"
}

display_error() {
	msg "A opção \"$1\" não existe"
	msg "Utilize 'ckx --help' para mais detalhes."

	exit "$FALSE"
}

display_help() {
	display_default_message
	msg ""
	msg " Exemplos:"
	msg "  ckx (Nenhuma opção)"
	msg "         Inicia o modo shell interativo."
	msg ""
	msg "  ckx --encrypt <file|dir>"
	msg "         Criptografa um arquivo ou diretório. Será exigido uma senha."
	msg ""
	msg "  ckx --decrypt <file.gpg>"
	msg "         Descriptografa um arquivo que esteja criptografado com gpg."
	msg ""
	msg " Opções:"
	msg ""
	msg "  -h, --help       Exibe esta mensagem."
	msg ""
	msg "  -v, --version    Exibe a versão do software."
	msg ""
	msg "  -l, --license    Exibe a licença do software."
	msg ""
	msg "  -e, --encrypt    Criptografa um arquivo com GPG usando chave simétrica."
	msg "                   É aplicado Tar + Gunzip caso seja um diretório."
	msg ""
	msg "  -d, --decrypt    Descriptografa um arquivo GPG."

	exit "$TRUE"
}

########################################################################################
#
# GPG
#
########################################################################################

gpg_encrypt_dir() {
	local dir="$1"
	local out="$2"
	: "${out:=${dir}.ckx}"
	tar -czf - "$dir" | gpg --yes "${GPG_ENC_OPTS[@]}" -c -o "$out"
}

gpg_decrypt_dir() {
	local dir="$1"
	gpg "${GPG_DEC_OPTS[@]}" -d "$dir" | tar -xzf -
}

########################################################################################
#
# ckx database mode
#
########################################################################################

ckxdb_help() {
	msg "SELECT -> seleciona um diretório (SELECT 'dir')"
	msg "CREATE -> cria um novo diretório (CREATE 'dir')"
	msg "REMOVE -> remove um diretório    (REMOVE 'dir')"
	msg "LIST   -> lista os diretórios"
	msg "CLEAR  -> limpa a tela"
	msg "HELP   -> exibe esta lista"
	msg "EXIT   -> termina o software"
}

ckxdb_title() {
	msg "\e[1;31m"
	msg '             ▄▄█▀▀▀█▄█████▀ ▀███▀▀███▀   ▀██▀'
	msg '           ▄██▀     ▀█ ██   ▄█▀    ███▄  ▄█'
	msg '           ██▀       ▀ ██ ▄█▀       ▀██▄█▀'
	msg '           ██          █████▄         ███'
	msg '           ██▄         ██  ███      ▄█▀▀██▄'
	msg '           ▀██▄     ▄▀ ██   ▀██▄   ▄█   ▀██▄'
	msg '             ▀▀█████▀▄████▄   ███▄██▄▄  ▄▄███▄'
	msg " a soldier's bravery is only recognized on the battlefield"
	msg "               --||////[CRYPTOKNIGHTX]////>"
	msg "\e[m"
}

ckxdb_decrypt() {
	local dir="$1"
	if gpg_decrypt_dir "$dir"; then
		sucess "$dir descriptografado com sucesso."
	else
		error "Algum erro ocorreu ao descriptografar $dir."
	fi
}

ckxdb_encrypt() {
	local dir="$1"
	dd if=/dev/random of="$dir"/.entropy bs=1M count=1 &>/dev/null
	if gpg_encrypt_dir "$dir"; then
		sucess "$dir criptografado com sucesso."
	else
		error "Algum erro ocorreu ao criptografar $dir."
	fi
}

ckxdb_list() {
	local data

	for data in "$CKX_DATA_DIR"/*; {
		if [[ -d "$data" ]]; then
			msg "\e[1;31m[!] ${data##*/} (descriptografado)\e[m"
		elif [[ -e "$data" ]]; then
			msg "\e[1;32m[+] ${data##*/}\e[m"
		fi
	}
}

ckxdb_cd() {
	local target="$1"

	[[ -d "$target" ]] && {
		CKXDB_BREAK=0
		return "$TRUE"
	}

	[[ -e "$target" ]] && {
		ckxdb_decrypt "$target"
		CKXDB_BREAK=0
		return "$TRUE"
	}

	warn "$target não existe."
	return "$FALSE"
}

ckxdb_rm() {
	local target="$1"

	[[ -z "$target" ]] && {
		warn "Nome não fornecido."
		return "$FALSE"
	}

	[[ -d "$target" || -e "$target" ]] || {
		warn "$target não existe."
		return "$FALSE"
	}

	read -rp "Deseja remover $target? (yes/N*) "
	[[ "$REPLY" == yes ]] && {
		if rm -rf "$target"; then
			sucess "$target removido com sucesso."
			return "$TRUE"
		else
			warn "Não foi possível remover $target."
			return "$FALSE"
		fi
	}
	warn "Operação cancelada."
	return "$FALSE"
}

ckxdb_create() {
	local name="$1"

	[[ -z "$name" ]] && {
		warn "Nome do diretório não fornecido."
		return "$FALSE"
	}

	[[ -d "$name" || -e "$name" || -e "${name}.ckx" ]] && {
		warn "$name já existe."
		return "$FALSE"
	}

	if mkdir "$name"; then
		sucess "$name criado com sucesso."
		return "$TRUE"
	else
		warn "Não foi possível criar o diretório $name."
		return "$FALSE"
	fi
}

ckxdb_run_shell() {
	local path="$1"
	(
		export HISTFILE="$path/.bash_history"
		export HISTCONTROL=ignoreboth
		export HISTSIZE=100
		exec bash --norc --noprofile -l -i
	)
}

ckxdb() {
	declare -g CKX_DATA_DIR="${CKX_DEFAULT_DIR}/data"

	[[ -d "$CKX_DEFAULT_DIR" ]] ||
		mkdir -p "$CKX_CONFIGS_DIR" "$CKX_DATA_DIR"

	builtin cd "$CKX_DATA_DIR"

	declare -g CKXDB_BREAK=1
	local __ckxdb__cmd
	local __ckxdb__cmd_args
	local __ckxdb__arg
	local __ckxdb__target
	local __ckxdb__path
	while :; do
		while (( CKXDB_BREAK )); do
			read -rep 'ckx-database > ' __ckxdb__cmd_args

			[[ -z "$__ckxdb__cmd_args" ]] && continue

			# shellcheck disable=SC2086
			set -- $__ckxdb__cmd_args
			__ckxdb__cmd="$1"
			__ckxdb__arg="${2%/}"
			__ckxdb__target="${__ckxdb__arg%.ckx}"
			__ckxdb__path="${CKX_DATA_DIR}/${__ckxdb__target}"
			case "${__ckxdb__cmd,,}" in
				h*) ckxdb_help ;;
				l*) ckxdb_list ;;
				cd | sel*) ckxdb_cd "$__ckxdb__arg" ;;
				rm | rem*) ckxdb_rm "$__ckxdb__arg" ;;
				cr*) ckxdb_create "$__ckxdb__arg" ;;
				cl*) clear ;;
				exit) exit "$TRUE" ;;
				*) warn "O comando \"$__ckxdb__cmd\" é inválido." ;;
			esac
		done

		builtin cd "$__ckxdb__target"

		ckxdb_title
		warn "Utilize 'exit' para criptografar os arquivos em $PWD"
		msg ""

		ckxdb_run_shell "$__ckxdb__path"
		CKXDB_BREAK=1

		builtin cd "$CKX_DATA_DIR"
		ckxdb_encrypt "$__ckxdb__target" && rm -r "$__ckxdb__target"
	done

	exit "$?"
}

########################################################################################
#
# encrypt and decrypt
#
########################################################################################

ckx_encrypt() {
	local file="${1%/}"

	[[ -z "$file" ]] && {
		msg "ckx [-e|--encrypt] [FILE|DIR]"
		exit "$FALSE"
	}

	[[ -d "$file" ]] && {
		gpg_encrypt_dir "$file" "${file}.tgz.gpg" ||
			fatal "Algum erro ocorreu ao criptografar ${file}."
		exit "$TRUE"
	}

	[[ -e "$file" ]] || fatal "$file não existe."

	gpg "${GPG_ENC_OPTS[@]}" -o "${file}.gpg" -c "$file" ||
		fatal "Algum erro ocorreu ao criptografar ${file}."
}

ckx_decrypt() {
	local file="$1"

	[[ -z "$file" ]] && {
		msg "ckx [-d|--decrypt] [FILE.gpg]"
		exit "$FALSE"
	}

	[[ -d "$file" || "${file#*.}" == "gpg" ]] &&
		fatal "Só pode criptografar arquivos GPG."
	[[ -e "$file" ]] || fatal "$file não existe."

	gpg -o "${file%.gpg}" --no-symkey-cache -d "$file" ||
		fatal "Algum erro ocorreu ao descriptografar ${file}."
}

#----------------------------------------------------------------------------------+
####################################### MAIN #####################################

(( $# == 0 )) && {
	display_default_message
	ckxdb
}

case "$1" in
	-h|--help)    display_help       ;;
	-l|--license) display_license    ;;
	-v|--version) display_version    ;;
	--configure)  config_gpg         ;;
	-e|--encrypt) ckx_encrypt "$2"   ;;
	-d|--decrypt) ckx_decrypt "$2"   ;;
	*)            display_error "$1" ;;
esac

exit "$?"

##################################### END MAIN ###################################
#----------------------------------------------------------------------------------+
